create extension if not exists pgcrypto;

create table if not exists public.beta_release_assets (
  platform text primary key check (platform in ('mac-arm64', 'windows-x64')),
  download_url text not null check (download_url ~ '^https://'),
  version text not null,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.beta_downloads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('mac-arm64', 'windows-x64')),
  version text not null,
  requested_at timestamptz not null default now()
);

create table if not exists public.telemetry_events (
  id bigint generated by default as identity primary key,
  installation_id uuid not null,
  event text not null check (event in (
    'app_started', 'telemetry_enabled', 'recording_started', 'recording_completed',
    'recording_failed', 'transcription_completed', 'transcription_failed', 'calendar_created'
  )),
  app_version text not null,
  platform text not null check (platform in ('darwin', 'win32')),
  architecture text not null,
  properties jsonb not null default '{}'::jsonb,
  received_at timestamptz not null default now()
);

alter table public.beta_release_assets enable row level security;
alter table public.beta_downloads enable row level security;
alter table public.telemetry_events enable row level security;

create index if not exists beta_downloads_user_requested_idx on public.beta_downloads(user_id, requested_at desc);
create index if not exists telemetry_events_installation_received_idx on public.telemetry_events(installation_id, received_at desc);

-- Tables intentionally have no client policies. Edge Functions use the service role
-- after validating either the signed-in user or the telemetry event schema.
